resources:
    App\Entity\Comment:
        class: App\Entity\Comment
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters: ['app.api_platform.filter.comment.search']
            ApiPlatform\Metadata\Get: ~
            ApiPlatform\Metadata\Post: ~
            ApiPlatform\Metadata\Put: ~
            ApiPlatform\Metadata\Patch: ~
            ApiPlatform\Metadata\Delete: ~
        normalizationContext:
            groups: ['comment:read']
        denormalizationContext:
            groups: ['comment:write']
