resources:
    App\Entity\Post:
        class: App\Entity\Post
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters: ['app.api_platform.filter.post.search']
                security: "is_granted('IS_AUTHENTICATED_FULLY')"
            ApiPlatform\Metadata\Get:
                security: "is_granted('IS_AUTHENTICATED_FULLY')"
            ApiPlatform\Metadata\Post:
                security: "is_granted('IS_AUTHENTICATED_FULLY')"
            ApiPlatform\Metadata\Put:
                security: "is_granted('IS_AUTHENTICATED_FULLY')"
            ApiPlatform\Metadata\Patch:
                security: "is_granted('IS_AUTHENTICATED_FULLY')"
            ApiPlatform\Metadata\Delete:
                security: "is_granted('IS_AUTHENTICATED_FULLY')"
        normalizationContext:
            groups: ['post:read']
        denormalizationContext:
            groups: ['post:write']
