resources:
    App\Entity\Post:
        class: App\Entity\Post
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters: ['app.api_platform.filter.post.search']
            ApiPlatform\Metadata\Get: ~
            ApiPlatform\Metadata\Post: ~
            ApiPlatform\Metadata\Put: ~
            ApiPlatform\Metadata\Patch: ~
            ApiPlatform\Metadata\Delete: ~
        normalizationContext:
            groups: ['post:read']
        denormalizationContext:
            groups: ['post:write']
