App\Entity\User:
    attributes:
        id:
            groups: ['user:read']
        email:
            groups: ['user:read', 'user:write']
        roles:
            groups: ['user:read', 'user:write']
        password:
            groups: ['user:write']
